controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: fake_hand_controller
    joints:
      - qbhand_synergy_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: hand
    pose: open