# # Simulation settings for using moveit_sim_controllers
# moveit_sim_hw_interface:
#   joint_model_group: arm
#   joint_model_group_pose: home
# # Settings for ros_control_boilerplate control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01

# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - joint_1
#     - joint_2
#     - joint_3
#     - joint_4
#     - joint_5
#     - joint_6
#     - joint_7
#     - qbhand_synergy_joint
#   sim_control_mode: 1  # 0: position, 1: velocity

joint_state_controller:
  type: joint_state_controller/JointStateController # commented on friday by ER
  # type: position_controllers/JointTrajectoryController # added on friday by ER
  publish_rate: 50

controller_list:
  - name: "gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7


# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  # type: joint_state_controller/JointStateController
  type: position_controllers/JointTrajectoryController
  publish_rate: 50


controller_list:
  - name: /qbhand/control/qbhand_synergy_trajectory_controller
  # - name: "qbhand_synergy_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      [qbhand_synergy_joint]